### ISSUE TITLE
Ludii - Analysis metric outputing conflicting numbers with swap rules

### ISSUE THREAD

**Issue by David-Ciz** [Ludeme/Ludii#3]
Hello, I'm currently conducting some experiments on the game Hex using the "Evaluation Dialog" and I noticed that when I allow swap rules, the Player 1 win rate and AdvantageP1 numbers do not match and Balance also doesn't reflect the reported win rates at times. Here is the console output for an experiment on 100 trials, with no timeouts and no draws, using MC-GRAVE AI agent:

> 
> Analysing Hex [Board Size/11x11, Swap Rules/On, End Rules/Standard]
> 
> Please don't touch anything until complete! 
> Generating trials: 
> ....................................................................................................
> Calculating metrics: 
> AdvantageP1
> Balance
> Completion
> Drawishness
> Timeouts
> Board Coverage Default
> Decisiveness Moves
> Ideal Duration
> 
> 
> Agent type: MC-GRAVE
> Draw likelihood: 0%
> Timeout likelihood: 0%
> Average number of moves per game: 30.76
> Player 1 win rate: 58%
> Player 2 win rate: 42%
> 
> AdvantageP1: 0.56 (weight: 1.0)
> Balance: 0.88 (weight: 1.0)
> Completion: 1 (weight: 1.0)
> Drawishness: 0 (weight: 1.0)
> Timeouts: 0 (weight: 1.0)
> Board Coverage Default: 0.25405 (weight: 1.0)
> Decisiveness Moves: 0.42 (weight: 1.0)
> Ideal Duration: 0.43987 (weight: 1.0)
> Final Score: 3.55391

When I look into EvaluateGame function, the win rate is calculated using "RankUtils.agentUtilities(context);" where it is explicitly checked if players swapped positions, but metrics for Advantage and Balance are calculated using "trial.status().winner()" with no further checks. If the winner is wrongly attributed to a player index before the swap, this would explain this discrepancy. 

I'm not that well versed in Java and maybe I overlooked something, but can you please check my findings? The problem is reproducible on Ludii-1.2.8 and a version close to the current master.

Thank you,

David

**Comment by stepmat** [comment]
Hi David,

Thanks for pointing this issue out. You are correct that this was indeed a bug.
I have fixed this issue in the dev branch of Ludii, and it will also be fixed in the next official release.

Cheers,
Matthew

**Comment by David-Ciz** [comment]
Hi Matthew,

thanks for the fast response, glad to help.

Have a good day
